server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/floodguard
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

app:
  jwt:
    secret: ${JWT_SECRET:OxK6lmWkHqkFSUaRoAo+ZB0dNM4hzkZRzoEGZNtwTGg=}
    expiration: 86400000 # 24 hours in milliseconds
  file:
    upload-dir: ./uploads
    allowed-types: image/jpeg,image/png,image/gif
    max-size: 5242880 # 5MB in bytes

logging:
  level:
    com.floodguard: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG 